//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa_X
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DadosLogin
    {
        public int Usuario_ID { get; set; }
        public string Usuario { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public Nullable<int> Deleted { get; set; }
    }
}
