//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresa_X
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Funcionarios
    {
        public int Funcionario_ID { get; set; }
        public string Nome { get; set; }
        public string Função { get; set; }
        public string Setor { get; set; }
        public Nullable<int> Setor_ID { get; set; }
        public Nullable<int> DELETED { get; set; }
    }
}
